"""
SMART Data Parser and Normalizer

Parses smartctl JSON/text output and normalizes manufacturer-specific values.
Provides severity assessment for each attribute.

Key challenges handled:
- Seagate's 48-bit composite raw values (Raw_Read_Error_Rate, Seek_Error_Rate)
- Manufacturer-specific threshold interpretations
- Pre-fail vs Old_age classification confusion
- Normalized 1-100 health scoring

Attribute reference data imported from smartmontools drivedb.h
(see smartdb.py, auto-generated by scripts/generate_smartdb.py).
"""

import json
import logging
import re
from dataclasses import dataclass, field

from .smartdb import SEAGATE_COMPOSITE, SMART_ATTR_NAMES

logger = logging.getLogger(__name__)

# Seagate composite attributes — authoritative list from smartmontools drivedb.h
# smartctl uses 48-bit composite encoding for these on Seagate drives.
# Extended beyond drivedb.h defaults with additional Seagate-specific attributes
# observed in practice (end-to-end errors, uncorrectables, etc.).
SEAGATE_COMPOSITE_ATTRS = SEAGATE_COMPOSITE | {
    184,  # End-to-End_Error
    187,  # Reported_Uncorrect
    188,  # Command_Timeout
    190,  # Airflow_Temperature
    195,  # Hardware_ECC_Recovered
    198,  # Offline_Uncorrectable
    199,  # UDMA_CRC_Error_Count
    240,  # Head_Flying_Hours
}

# Attribute IDs that are critical regardless of normalized value
CRITICAL_ATTR_IDS = {
    5,  # Reallocated_Sector_Ct
    187,  # Reported_Uncorrect
    188,  # Command_Timeout
    196,  # Reallocated_Event_Count
    197,  # Current_Pending_Sector
    198,  # Offline_Uncorrectable
    201,  # Soft_Read_Error_Rate (SSD)
    231,  # SSD_Life_Left / Temperature
    233,  # Media_Wearout_Indicator
}

# Severity thresholds for critical attributes
# (threshold = raw_value above which we flag)
CRITICAL_THRESHOLDS = {
    5: 1,  # Any reallocated sector is concerning
    187: 1,  # Any uncorrectable error
    188: 1,  # Any command timeout
    196: 1,  # Any reallocation event
    197: 1,  # Any pending sector
    198: 1,  # Any offline uncorrectable
}

# SMART attribute type meanings
ATTRIBUTE_TYPES = {
    "Pre-fail": "Tracked since manufacturing (not necessarily failing)",
    "Old_age": "Degrades with use/wear (normal aging)",
}


@dataclass
class SmartAttribute:
    """A single SMART attribute reading."""

    attr_id: int = 0
    name: str = ""
    flags: str = ""  # "POSR-K" style flags
    attr_type: str = ""  # "Pre-fail" or "Old_age"
    updated: str = ""  # "Always" or "Offline"
    when_failed: str = ""  # "" or "-" or timestamp
    raw_value: int = 0
    value: int = 0  # Normalized current value (1-100/253)
    worst: int = 0  # Normalized worst ever value
    thresh: int = 0  # Failure threshold
    is_critical: bool = False
    severity: str = "ok"  # ok, warning, critical
    note: str = ""


@dataclass
class SmartDevice:
    """Complete SMART data for one device."""

    device_path: str = ""
    model: str = ""
    serial: str = ""
    firmware: str = ""
    capacity: str = ""
    device_type: str = ""  # ATA, NVMe, SCSI, SAT
    smart_supported: bool = False
    smart_enabled: bool = False
    overall_health: str = ""  # "PASSED" or "FAILED"
    power_on_hours: int = 0
    power_cycle_count: int = 0
    temperature: int = 0
    attributes: list[SmartAttribute] = field(default_factory=list)
    self_test_log: list[dict] = field(default_factory=list)
    error_log: list[dict] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    is_seagate: bool = False
    health_score: int = 100  # 0-100 normalized health


def parse_seagate_raw_value(attr_id: int, raw: int) -> int:
    """
    Extract the meaningful portion of a Seagate composite raw value.

    Seagate encodes multiple values into a 48-bit raw value.
    For most attributes, the lower 32 bits contain the actual count.
    """
    if attr_id not in SEAGATE_COMPOSITE_ATTRS:
        return raw

    # For Seagate composite values, extract the actual count from
    # the lower 32 bits
    return raw & 0xFFFFFFFF


def assess_attribute_severity(attr: SmartAttribute, is_seagate: bool) -> str:
    """
    Assess the severity of a single SMART attribute.

    Returns: "ok", "warning", or "critical"
    """
    # Check if it's a critical attribute
    if attr.attr_id in CRITICAL_ATTR_IDS:
        raw = attr.raw_value
        if is_seagate and attr.attr_id in SEAGATE_COMPOSITE_ATTRS:
            raw = parse_seagate_raw_value(attr.attr_id, raw)

        threshold = CRITICAL_THRESHOLDS.get(attr.attr_id, 1)
        if raw >= threshold:
            return "critical"

    # Check if normalized value is below or near threshold
    if attr.value <= attr.thresh:
        return "critical"

    # Warning if value is within 10% of threshold
    value_range = 100  # Normalized range is typically 1-100
    if attr.thresh > 0:
        margin = attr.value - attr.thresh
        if margin < value_range * 0.1:
            return "warning"

    # Pre-fail attributes with declining trend
    if attr.attr_type == "Pre-fail" and attr.value < 50:
        return "warning"

    return "ok"


def compute_health_score(device: SmartDevice) -> int:
    """
    Compute a 0-100 health score for a device.

    Factors:
    - Overall SMART health status
    - Critical attribute values
    - Self-test results
    - Temperature (extreme values)
    """
    score = 100

    # Overall health status
    if device.overall_health == "FAILED":
        return 0

    # Deduct for each attribute severity
    for attr in device.attributes:
        if attr.severity == "critical":
            score -= 25
        elif attr.severity == "warning":
            score -= 10

    # Deduct for failed self-tests
    for test in device.self_test_log:
        status = test.get("status", "").lower()
        if any(
            keyword in status
            for keyword in ("failed", "failure", "aborted", "interrupted")
        ):
            score -= 15

    # Temperature penalty (extreme values)
    if device.temperature > 60:
        score -= 10
    elif device.temperature > 55:
        score -= 5

    return max(0, min(100, score))


def classify_device_type(smart_output: str) -> str:
    """Classify the device type from smartctl output."""
    output_lower = smart_output.lower()
    if "nvme" in output_lower:
        return "NVMe"
    elif "scsi" in output_lower:
        return "SCSI"
    elif "sat" in output_lower:
        return "SAT"
    else:
        return "ATA"


def detect_manufacturer(model: str) -> tuple[str, bool]:
    """
    Detect drive manufacturer and whether it uses non-standard encoding.

    Returns: (manufacturer_name, uses_non_standard_encoding)
    """
    model_upper = model.upper()

    # Seagate: full brand name or model prefix (ST followed by digits)
    seagate_markers = {"SEAGATE", "IRONWOLF", "EXOS"}
    if any(m in model_upper for m in seagate_markers):
        return "Seagate", True
    # Seagate model numbers start with ST + digits (e.g., ST4000VN008)
    if (
        model_upper.startswith("ST")
        and len(model_upper) > 2
        and model_upper[2].isdigit()
    ):
        return "Seagate", True

    wd_markers = {"WDC", "WESTERN", "WD-", "WD "}
    if any(m in model_upper for m in wd_markers):
        return "Western Digital", False

    toshiba_markers = {"TOSHIBA", "MG", "DT", "HDWG"}
    if any(m in model_upper for m in toshiba_markers):
        return "Toshiba", False

    samsung_markers = {"SAMSUNG", "MZ-", "MZ7", "860", "870", "970", "980", "990"}
    if any(m in model_upper for m in samsung_markers):
        return "Samsung", False

    intel_markers = {"INTEL", "SSDSC", "D3-S", "P4", "P5"}
    if any(m in model_upper for m in intel_markers):
        return "Intel", False

    return "Unknown", False


def parse_smart_json(data: dict) -> SmartDevice:
    """
    Parse smartctl JSON output into a normalized SmartDevice.

    smartctl -j -a /dev/sdX produces structured JSON.
    """
    device = SmartDevice()

    # Device info
    device_info = data.get("device", {})
    device.device_path = device_info.get("name", "")
    device.device_type = classify_device_type(json.dumps(data))

    identity = data.get("model_name", "")
    device.model = identity
    device.serial = data.get("serial_number", "")
    device.firmware = data.get("firmware_version", "")

    # Capacity
    user_capacity = data.get("user_capacity", {})
    if isinstance(user_capacity, dict):
        device.capacity = user_capacity.get("string", "")
    else:
        device.capacity = str(user_capacity)

    # SMART status
    smart_status = data.get("smart_status", {})
    device.smart_supported = data.get("smartcapable", False)
    device.smart_enabled = data.get("smart_enabled", {}).get("value", False)
    device.overall_health = "PASSED" if smart_status.get("passed", False) else "FAILED"

    # Detect manufacturer
    _, is_seagate = detect_manufacturer(device.model)
    device.is_seagate = is_seagate

    # Power-on hours
    power_on = data.get("power_on_time", {})
    if isinstance(power_on, dict):
        device.power_on_hours = power_on.get("hours", 0)

    power_cycle = data.get("power_cycle_count", 0)
    if isinstance(power_cycle, dict):
        device.power_cycle_count = power_cycle.get("count", 0)
    else:
        device.power_cycle_count = int(power_cycle) if power_cycle else 0

    # Temperature
    temperature = data.get("temperature", {})
    if isinstance(temperature, dict):
        device.temperature = temperature.get("current", 0)
    elif isinstance(temperature, (int, float)):
        device.temperature = int(temperature)

    # Parse attributes
    ata_attrs = data.get("ata_smart_attributes", {}).get("table", [])
    for attr_data in ata_attrs:
        attr_id = int(attr_data.get("id", 0))
        attr_name = attr_data.get("name", "")
        # Fallback: use smartmontools drivedb.h canonical name
        if not attr_name and attr_id in SMART_ATTR_NAMES:
            attr_name = SMART_ATTR_NAMES[attr_id]
        attr = SmartAttribute(
            attr_id=attr_id,
            name=attr_name,
            flags=attr_data.get("flags", {}).get("string", ""),
            attr_type=attr_data.get("when_failed", ""),
            updated=attr_data.get("value", 0),
            when_failed=attr_data.get("when_failed", ""),
            raw_value=int(attr_data.get("raw", {}).get("value", 0)),
            value=int(attr_data.get("value", 0)),
            worst=int(attr_data.get("worst", 0)),
            thresh=int(attr_data.get("thresh", 0)),
            is_critical=attr_data.get("id", 0) in CRITICAL_ATTR_IDS,
        )

        # Correct type mapping (when_failed is actually "pre-fail" or "old-age")
        flags_str = attr_data.get("flags", {}).get("string", "")
        if "P" in flags_str:
            attr.attr_type = "Pre-fail"
        elif "O" in flags_str:
            attr.attr_type = "Old_age"

        attr.severity = assess_attribute_severity(attr, device.is_seagate)

        # Generate human-readable notes for critical attributes
        if attr.severity in ("warning", "critical"):
            raw = attr.raw_value
            if device.is_seagate and attr.attr_id in SEAGATE_COMPOSITE_ATTRS:
                raw = parse_seagate_raw_value(attr.attr_id, raw)
            attr.note = f"Raw value: {raw} (normalized: {attr.value}/{attr.thresh})"
            device.warnings.append(f"{attr.name}: {attr.severity} - {attr.note}")

        device.attributes.append(attr)

    # Self-test log
    self_test_log = data.get("ata_smart_self_test_log", {}).get("standard", [])
    for test in self_test_log:
        device.self_test_log.append(
            {
                "type": test.get("type", {}).get("string", ""),
                "status": test.get("status", {}).get("string", ""),
                "timestamp": test.get("lifetime_hours", 0),
            }
        )

    # Error log
    error_log = data.get("ata_smart_error_log", {}).get("count", 0)
    if isinstance(error_log, dict):
        error_count = error_log.get("count", 0)
    else:
        error_count = int(error_log)
    if error_count > 0:
        device.error_log.append({"count": error_count})
        if error_count > 100:
            device.warnings.append(f"SMART error log has {error_count} entries")

    # Compute health score
    device.health_score = compute_health_score(device)

    return device


def parse_smart_text(output: str) -> SmartDevice:
    """
    Parse smartctl text output as fallback.

    Used when JSON output is not available.
    """
    device = SmartDevice()
    device.attributes = []

    # Basic device info
    for line in output.split("\n"):
        if line.startswith("Device:"):
            device.device_path = line.split(":", 1)[1].strip()
        elif line.startswith("Model Family:"):
            pass  # Could extract family
        elif line.startswith("Device Model:"):
            device.model = line.split(":", 1)[1].strip()
        elif line.startswith("Serial Number:"):
            device.serial = line.split(":", 1)[1].strip()
        elif line.startswith("SMART overall-health"):
            if "PASSED" in line:
                device.overall_health = "PASSED"
            elif "FAILED" in line:
                device.overall_health = "FAILED"
        elif line.startswith("SMART support is: Enabled"):
            device.smart_enabled = True

    # Detect manufacturer
    _, is_seagate = detect_manufacturer(device.model)
    device.is_seagate = is_seagate

    # Parse attribute table
    attr_pattern = re.compile(
        r"^\s*(\d+)\s+(\S+)\s+([0-9x]+)\s+(\d+)\s+(\d+)\s+(\d+)\s+"
        r"([-\d]+)\s+(\d+)\s+(\d+)\s+(\d+)\s+([0-9]+)\s*$"
    )
    in_attr_table = False
    for line in output.split("\n"):
        if "ID#" in line and "ATTRIBUTE_NAME" in line:
            in_attr_table = True
            continue
        if in_attr_table:
            match = attr_pattern.match(line)
            if match:
                raw_val = int(match.group(11))
                attr = SmartAttribute(
                    attr_id=int(match.group(1)),
                    name=match.group(2),
                    flags=match.group(3),
                    attr_type="Pre-fail" if "P" in match.group(3) else "Old_age",
                    updated="",
                    when_failed="",
                    raw_value=raw_val,
                    value=int(match.group(4)),
                    worst=int(match.group(5)),
                    thresh=int(match.group(6)),
                    is_critical=int(match.group(1)) in CRITICAL_ATTR_IDS,
                )
                attr.severity = assess_attribute_severity(attr, device.is_seagate)
                device.attributes.append(attr)
            elif line.strip() == "" or not line.startswith(" "):
                in_attr_table = False

    device.health_score = compute_health_score(device)
    return device


def format_smart_summary(device: SmartDevice) -> str:
    """
    Format a human-readable summary of device health.

    This is the primary output for the MCP tool.
    """
    lines = []
    lines.append(f"Device: {device.device_path}")
    lines.append(f"Model:  {device.model}")
    lines.append(f"Serial: {device.serial}")
    lines.append(f"Firmware: {device.firmware}")
    if device.capacity:
        lines.append(f"Capacity: {device.capacity}")
    lines.append(f"Type:   {device.device_type}")
    lines.append("")

    # Health overview
    manufacturer, is_seagate = detect_manufacturer(device.model)
    lines.append(f"Manufacturer: {manufacturer}")
    if is_seagate:
        lines.append("  ⚠️  Seagate: raw values use 48-bit composite encoding")
        lines.append("     (normalized values used for assessment)")
    lines.append("")

    lines.append(f"SMART Status:     {device.overall_health}")
    lines.append(f"Health Score:     {device.health_score}/100")
    lines.append(f"Power-On Hours:   {device.power_on_hours:,}")
    lines.append(f"Power Cycles:     {device.power_cycle_count:,}")
    lines.append(f"Temperature:      {device.temperature}°C")
    lines.append("")

    # Warnings and critical items
    critical_attrs = [a for a in device.attributes if a.severity == "critical"]
    warning_attrs = [a for a in device.attributes if a.severity == "warning"]

    if critical_attrs:
        lines.append("🔴 CRITICAL:")
        for attr in critical_attrs:
            lines.append(f"   - {attr.name}: {attr.note}")

    if warning_attrs:
        lines.append("🟡 WARNING:")
        for attr in warning_attrs:
            lines.append(f"   - {attr.name}: {attr.note}")

    if not critical_attrs and not warning_attrs:
        lines.append("✅ No issues detected")

    # Self-test summary
    failed_tests = [
        t
        for t in device.self_test_log
        if t.get("status", "").lower() in ("failed", "aborted", "interrupted")
    ]
    if failed_tests:
        lines.append("")
        lines.append("🔴 Failed self-tests:")
        for test in failed_tests:
            lines.append(
                f"   - {test['type']}: {test['status']} "
                f"(at {test['timestamp']:,} hours)"
            )

    # Error log
    if device.error_log:
        for entry in device.error_log:
            if entry.get("count", 0) > 0:
                lines.append(f"\n🟡 SMART error log: {entry['count']} entries")

    return "\n".join(lines)
